yml
name: Discord bot for MovieNight server
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: stops pm2
      run: npx pm2 stop "npm run start"
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: starts pm2
      run: npx pm2 start "npm run start"